export const PARTICLE_RADIUS: number = 3;
export const CANVAS_WIDTH: number = 500;
export const CANVAS_HEIGHT: number = 500;
export const MAX_SPEED: number = 3;
export const NUMBER_OF_PARTICLES: number = 300;
export const D_T = 100;
export const INFECTION_PROBABILITY = 0.03;
export const SPREAD_RADIUS = 10;
export const INIT_INFECTED_PROBABILITY = 0.005;